name: app
description: A new Flutter project.

publish_to: "none"

version: 1.0.6+7

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.10.5"

dependencies:
  flutter:
    sdk: flutter

  yar:
    git:
      url: https://github.com/spideythewebhead/yar.git
      ref: main
  firebase_core: 1.12.0
  cloud_functions: 3.2.7
  firebase_auth: 3.3.7
  flutter_riverpod: 2.0.0-dev.1
  freezed_annotation: 1.1.0
  json_annotation: 4.4.0
  google_mobile_ads: 1.2.0
  share_plus: 4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_launcher_icons: 0.9.2
  flutter_lints: 1.0.4
  freezed: 1.1.1
  json_serializable: 6.1.4
  build_runner:
  mockito: 5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/logos/

flutter_icons:
  android: ic_launcher
  ios: false
  image_path: "assets/logos/logo.png"
