name: app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  yar:
    path: ../../yar
  firebase_core: 1.12.0
  cloud_functions: 3.2.7
  firebase_auth: 3.3.7
  flutter_riverpod: 2.0.0-dev.1
  freezed_annotation: 1.1.0
  json_annotation: 4.4.0
  google_mobile_ads: 1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 1.0.4
  freezed: 1.1.1
  json_serializable: 6.1.4
  build_runner:
  mockito: 5.1.0

flutter:
  uses-material-design: true
