name: testing
on: push

jobs:
  unit-test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Clone Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "2.10.3"
      - run: flutter doctor -v

      - name: Checkout
        uses: actions/checkout@v2
      - run: flutter pub get

      - name: Generate files
        run: flutter pub run build_runner build

      - name: Flutter analyze
        run: flutter analyze

      - name: Flutter format (exit on change)
        run: flutter format --set-exit-if-changed --dry-run .

      - name: Flutter test
        run: flutter test
